services:
  dev:
    image: ghcr.io/astral-sh/uv:debian-slim
    volumes:
      - .:${PWD}
      - ${PWD}.venv
      - paas-uv-cache:/root/.cache/uv
      - paas-uv-local:/root/.local/share/uv
    working_dir: ${PWD}
    command: bash

volumes:
  paas-uv-cache:
  paas-uv-local:
